apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-lab
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.60-192.168.1.70
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-lab