apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: drozdzikm@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector: {}
        dns01:
          route53:
            region: eu-central-1
            accessKeyID: AKIATPUFS5EESLDSNXEP
            hostedZoneID: Z26YK7PC8DTDJ4
            secretAccessKeySecretRef:
              name: route53-creds
              key: secret-access-key
